version: '3.4'

services:
  db_server:
    image: postgres
    container_name: db_server
    environment:
      POSTGRES_DB: ${STRAPI_DB_NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      PGDATA: /data/db
    command: -p ${DB_PORT}  # change default port to DB_PORT
    expose:
      - ${DB_PORT}  # Publishes DB_PORT to other containers but NOT to host machine
    volumes:
      - ${DB_DATA_DIR}:/data/db
    restart: unless-stopped


  db_adminer:
    image: dpage/pgadmin4
    container_name: db_adminer
    depends_on:
      - db_server
    environment:
      PGADMIN_DEFAULT_EMAIL: ${EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PASSWORD}
    expose:
      - 80
    restart: unless-stopped

  server:
    image: strapi/strapi
    container_name: server
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: ${STRAPI_DB_NAME}
      DATABASE_HOST: db_server
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USERNAME: ${USER}
      DATABASE_PASSWORD: ${PASSWORD}
    expose:
      - 1337
    volumes:
      - ${STRAPI_APP_DIR}:/srv/app
    depends_on:
      - db_server
    restart: unless-stopped
  
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    container_name: jenkins
    expose:
      - 8080
      - 50000
    volumes:
      - ${JENKINS_DATA_DIR}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  
  nginx:
    image: staticfloat/nginx-certbot
    container_name: nginx
    environment:
        CERTBOT_EMAIL: ${EMAIL}
    volumes:
      - ./nginx-conf.d:/etc/nginx/user.conf.d:ro
      - ${ENCRYPT_DIR}:/etc/letsencrypt
    ports:
      - 80:80/tcp
      - 443:443/tcp
    restart: unless-stopped
