version: '3.4'

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: ${STRAPI_DB_NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      PGDATA: /data/db
    command: -p ${DB_PORT}  # change default port to DB_PORT
    expose:
      - ${DB_PORT}  # Publishes DB_PORT to other containers but NOT to host machine
    volumes:
      - ${DB_DATA_DIR}:/data/db
    restart: unless-stopped


  db_adminer:
    image: dpage/pgadmin4
    container_name: db_adminer
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PASSWORD}
    command: -p ${DB_ADMINER_PORT}
    expose:
      - ${DB_ADMINER_PORT}
    restart: unless-stopped

  server:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: ${STRAPI_DB_NAME}
      DATABASE_HOST: db
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USERNAME: ${USER}
      DATABASE_PASSWORD: ${PASSWORD}
    command: -p ${STRAPI_PORT}
    expose:
      - ${STRAPI_PORT}
    volumes:
      - ${STRAPI_APP_DIR}:/srv/app
    depends_on:
      - db
  
  nginx:
    image: staticfloat/nginx-certbot
    environment:
        CERTBOT_EMAIL: ${EMAIL}
    volumes:
      - ./nginx-conf.d:/etc/nginx/user.conf.d:ro
      - ${ENCRYPT_DIR}:/etc/letsencrypt
    ports:
      - 80:80/tcp
      - 443:443/tcp
    depends_on:
      - server
    restart: unless-stopped
