version: '3.4'

services:
  db_server:
    image: postgres
    container_name: db_server
    environment:
      POSTGRES_DB: ${STRAPI_DB_NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      PGDATA: /data/db
    command: -p ${DB_PORT}  # change default port to DB_PORT
    expose:
      - ${DB_PORT}  # Publishes DB_PORT to other containers but NOT to host machine
    volumes:
      - ${DB_DATA_DIR}:/data/db
    restart: unless-stopped


  db_adminer:
    image: dpage/pgadmin4
    container_name: db_adminer
    depends_on:
      - db_server
    environment:
      PGADMIN_DEFAULT_EMAIL: ${EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PASSWORD}
    expose:
      - 80
    restart: unless-stopped

  server:
    image: strapi/strapi
    container_name: server
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: ${STRAPI_DB_NAME}
      DATABASE_HOST: db_server
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USERNAME: ${USER}
      DATABASE_PASSWORD: ${PASSWORD}
    expose:
      - 1337
    volumes:
      - ${STRAPI_APP_DIR}:/srv/app
    depends_on:
      - db_server
    restart: unless-stopped
  
  jenkins:
    image: docker.io/bitnami/jenkins:2-debian-10 # https://github.com/bitnami/bitnami-docker-jenkins
    container_name: jenkins
    environment:
      JENKINS_USERNAME: ${USER}
      JENKINS_PASSWORD: ${PASSWORD}
      # JENKINS_HOME: /jenkins/jenkins_home
      # DISABLE_JENKINS_INITIALIZATION: no
    expose:
      - 8080
      - 50000
      - 8443
    volumes:
      - jenkins_data:/bitnami/jenkins
    restart: unless-stopped
  
  nginx:
    image: staticfloat/nginx-certbot
    container_name: nginx
    environment:
        CERTBOT_EMAIL: ${EMAIL}
    volumes:
      - ./nginx-conf.d:/etc/nginx/user.conf.d:ro
      - ${ENCRYPT_DIR}:/etc/letsencrypt
    ports:
      - 80:80/tcp
      - 443:443/tcp
    depends_on:
      - server
    restart: unless-stopped

volumes:
  jenkins_data:
    driver: local