version: '3.4'

services:
  db_server:
    image: postgres:latest
    container_name: db_server
    environment:
      POSTGRES_DB: ${STRAPI_DB_NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      PGDATA: /data/db
    expose:
      - 5432
    volumes:
      - ${DB_DATA_DIR}:/data/db
    restart: unless-stopped


  db_adminer:
    image: dpage/pgadmin4:latest
    container_name: db_adminer
    depends_on:
      - db_server
    environment:
      PGADMIN_DEFAULT_EMAIL: ${EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PASSWORD}
    expose:
      - 80
    restart: unless-stopped

  server:
    image: strapi/strapi
    container_name: server
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: ${STRAPI_DB_NAME}
      DATABASE_HOST: db_server
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USERNAME: ${USER}
      DATABASE_PASSWORD: ${PASSWORD}
    expose:
      - 1337
    volumes:
      - ${STRAPI_APP_DIR}:/srv/app
    depends_on:
      - db_server
    restart: unless-stopped
  
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    container_name: jenkins
    expose:
      - 8080
      - 50000
    volumes:
      - ${JENKINS_DATA_DIR}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  
  nginx:
    image: nginx:latest
    container_name: nginx
    environment:
      STRAPI_DOMAIN: ${STRAPI_DOMAIN}
      # URL format http://${service name}:${service exposed port}
      # more about docker network see https://docs.docker.com/compose/networking/
      STRAPI_SERVER: http://server:1337
      WEB_DOMAIN: ${WEB_DOMAIN}
      JENKINS_DOMAIN: ${JENKINS_DOMAIN}
      JENKINS_SERVER: http://jenkins:8080
    volumes:
      - ./nginx-conf-templates:/etc/nginx/templates
      - ${PUBLIC_DIR}:/var/www/html
      - ${CERT_DIR}/conf:/etc/nginx/ssl
      - ${CERT_DIR}/data:/var/www/certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
    restart: unless-stopped

  certbot:
      image: certbot/certbot:latest
      container_name: certbot
      depends_on:
        - nginx
      command: certonly --webroot --webroot-path=/var/www/certbot \
        --email ${EMAIL} \
        --agree-tos \
        --no-eff-email \
        -d ${STRAPI_DOMAIN} \
        -d ${WEB_DOMAIN} \
        -d ${JENKINS_DOMAIN}
      volumes:
          - ${CERT_DIR}/conf:/etc/letsencrypt
          - ${CERT_DIR}/logs:/var/log/letsencrypt
          - ${CERT_DIR}/data:/var/www/certbot